
; 在后面的内容 不要加 "" 因为这样的话，在解析出来的数据就会变成 "127.0.0.1" 而不是 字符串类型的 127.0.0.1

[Redis]
Host = 127.0.0.1
Port = 6380
Password = 123456
[Mysql]
Host = 127.0.0.1
Port = 3306
User = hahaha
Password = 123456
Schema = JerryChat
[StatusServer]
Host = 127.0.0.1
Port = 50052
TCP_port = 10000
[ChatServers]
List = ChatServer1,ChatServer2
[SelfServer]
Host = 127.0.0.1
Port = 8090
RPCPort = 50053
Name = ChatServer1
[ChatServer2]
Host = 127.0.0.1
Port = 8091
Name = ChatServer2
RPCPort = 50054
[PeerServers]
Servers = ChatServer2
[ResourceServer]
Name = ResourceServer
Host = 127.0.0.1
Port  = 9090
RPCPort = 51055