
; �ں�������� ��Ҫ�� "" ��Ϊ�����Ļ����ڽ������������ݾͻ��� "127.0.0.1" ������ �ַ������͵� 127.0.0.1

[Redis]
Host = redis-master
Port = 6379
Password = 123456
SentinelHost = sentinel-1,sentinel-2,sentinel-3
SentinelPort = 26379,26379,26379
; Slave �˿ڣ���ѡ�����ŷָ������ú󴿶���������� Slave��
[Mysql]
Host = mysql-master
Port = 3306
User = root
Password = 123456
Schema = JerryChat
; Slave �˿ڣ���ѡ�����ú󴿶������� Slave��
SlaveHost = mysql-slave
SlavePort = 3306
[StatusServer]
Host = statusserver
Port = 50052
[ChatServers]
List = ChatServer1,ChatServer2
[ChatServer1]
Host = chatserver1
Port = 8090
RPCPort = 50053
Name = ChatServer1
[ChatServer2]
Host = chatserver2
Port = 8091
RPCPort = 50054
Name = ChatServer2
[ResourceServer]
Name = ResourceServer
Host = resourceserver
Port  = 9090
RPCPort = 51055
[JWT]
Secret = im-jwt-secret-2026
[Nginx]
Host = 127.0.0.1
Port = 8100