
; ں Ҫ "" ΪĻڽݾͻ "127.0.0.1"  ַ͵ 127.0.0.1

[Redis]
Host = redis
Port = 6379
Password = 123456
[Mysql]
Host = mysql
Port = 3306
User = hahaha
Password = 123456
Schema = JerryChat
[StatusServer]
Host = statusserver
Port = 50052
TCP_port = 10000
[ChatServers]
List = ChatServer1
[ChatServer1]
Host = chatserver1
Port = 8090
Name = ChatServer1
[ChatServer2]
Host = chatserver2
Port = 8091
Name = ChatServer2
[Limits]
ChatMaxConns = 1000
SeckillMaxConns = 300
ResourceMaxConns = 200
