
; �ں�������� ��Ҫ�� "" ��Ϊ�����Ļ����ڽ������������ݾͻ��� "127.0.0.1" ������ �ַ������͵� 127.0.0.1

[Redis]
Host = 127.0.0.1
Port = 6380
Password = 123456
SentinelHost = 127.0.0.1
SentinelPort = 26379,26380,26381
SlavePorts = 6381,6382
[Mysql]
Host = 127.0.0.1
Port = 3306
User = hahaha
Password = 123456
Schema = JerryChat
[SelfServer]
Name = reserver
Host = 0.0.0.0
Port  = 9090
RPCPort = 51055
UploadPath = E:\\FileUploadServer
DownloadPath = E:\\FileUploadServer
[ChatServer1]
Host = 127.0.0.1
Port = 8090
RPCPort = 50053
Name = ChatServer1
[ChatServer2]
Host = 127.0.0.1
Port = 8091
Name = ChatServer2
RPCPort = 50054
[ChatServers]
Servers = ChatServer1,ChatServer2
[StatusServer]
Host = 127.0.0.1
Port = 50052
TCP_port = 10000