
; �ں�������� ��Ҫ�� "" ��Ϊ�����Ļ����ڽ������������ݾͻ��� "127.0.0.1" ������ �ַ������͵� 127.0.0.1

[Redis]
Host = redis-master
Port = 6379
Password = 123456
SentinelHost = sentinel-1,sentinel-2,sentinel-3
SentinelPort = 26379,26379,26379
[Mysql]
Host = mysql-master
Port = 3306
User = hahaha
Password = 123456
Schema = JerryChat
[SelfServer]
Name = reserver
Host = 0.0.0.0
Port  = 9090
RPCPort = 51055
UploadPath = E:\\FileUploadServer
DownloadPath = E:\\FileUploadServer
[ChatServer1]
Host = chatserver1
Port = 8090
RPCPort = 50053
Name = ChatServer1
[ChatServer2]
Host = chatserver2
Port = 8091
Name = ChatServer2
RPCPort = 50054
[ChatServers]
Servers = ChatServer1,ChatServer2
[StatusServer]
Host = statusserver
Port = 50052
TCP_port = 10000